#!/bin/tcsh -fx

set apkDir = /Users/mjulia/Documents/D/data/soot/apks/

rm $apkDir/sootOutput/$1_$2.apk
mv $apkDir/sootOutput/$1.apk $apkDir/sootOutput/$1_$2.apk

jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore /Users/mjulia/Documents/D/data/android_tools/key/julia-release-key.keystore $apkDir/sootOutput/$1_$2.apk julia_key -storepass mjulia

jarsigner -verify -verbose $apkDir/sootOutput/$1_$2.apk

/Users/mjulia/Documents/D/GitRepositories/InstrumentAndroid/decompile sootOutput/$1_$2

~/Documents/eclipse/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s emulator-5554 uninstall $1
#~/Documents/eclipse/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s emulator-5554 logcat -c
~/Documents/eclipse/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s emulator-5554 install -r $apkDir/sootOutput/$1_$2.apk


#~/Documents/eclipse/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s emulator-5554 logcat > /Users/mjulia/Documents/D/data/soot/logs/$1_$2.logcat.log
