#!/bin/tcsh -fx

set apkDir = /Volumes/D/data/minst/apks
set andrTools = /Volumes/D/data/android_tools/
set appName = $1_$2

cd $apkDir/decompiled/asmOutput/$appName

jar cf ../$appName.jar *

echo "executing $andrTools/dex2jar-0.0.9.15/d2j-jar2dex.sh -f -o classes.dex ../$appName.jar"
$andrTools/dex2jar-0.0.9.15/d2j-jar2dex.sh -f -o classes.dex ../$appName.jar

#create new apk
cp $apkDir/orig/$1.apk $apkDir/asmOutput/$appName.apk
zip $apkDir/asmOutput/$appName.apk -d META-INF/CERT.SF
zip $apkDir/asmOutput/$appName.apk -d META-INF/CERT.RSA
zip -r $apkDir/asmOutput/$appName.apk classes.dex
rm classes.dex

#sign
#echo "executing $andrTools/dex2jar-0.0.9.15/d2j-apk-sign.sh -f -o $apkDir/asmOutput/$appName_signed.apk $apkDir/asmOutput/$appName.apk"
#$andrTools/dex2jar-0.0.9.15/d2j-apk-sign.sh -f -o $apkDir/asmOutput/$appName_signed.apk $apkDir/asmOutput/$appName.apk
#mv $apkDir/asmOutput/$appName_signed.apk $apkDir/asmOutput/$appName.apk


jarsigner -sigalg SHA1withRSA -digestalg SHA1 -keystore $andrTools/key/julia-release-key.keystore $apkDir/asmOutput/$appName.apk julia_key -storepass mjulia
jarsigner -verify $apkDir/asmOutput/$appName.apk

#echo "executing /Applications/JD-GUI.app/Contents/MacOS/jd-gui $apkDir/decompiled/asmOutput/$appName.jar"
#/Applications/JD-GUI.app/Contents/MacOS/jd-gui $apkDir/decompiled/asmOutput/$appName.jar &
