#!/bin/tcsh -fx

set apkDir = /Volumes/D/data/minst/apks/user_experiment

/Volumes/D/data/android_tools/dex2jar-0.0.9.15/d2j-dex2jar.sh $apkDir/orig/$1.apk -o $apkDir/decompiled/orig/$1_dex2jar.jar --force

rm -r $apkDir/decompiled/orig/$1
rm -r $apkDir/decompiled/asmOutput/$1
mkdir $apkDir/decompiled/orig/$1

cd $apkDir/decompiled/orig/$1
jar xf $apkDir/decompiled/orig/$1_dex2jar.jar

#/Applications/JD-GUI.app/Contents/MacOS/jd-gui $apkDir/decompiled/orig/$1_dex2jar.jar &
